### ISSUE TITLE
ATTENTION!!!

### ISSUE THREAD

**Issue by 4eckah78** [pmpu-133/general#2]
Can sm1 plz say y the heck is clear() in arr.h not working? Or mb smth else wrong?

**Comment by exp101t** [comment]
Do you know how issue should looks like? You should say what method doesn't work properly, why do you think so and so on. I just tested this code and didn't find any error (the only one is that `Array::size` field doesn't become `0` after calling `Array::clear()`).
**P.S.** And please, don't write in leet. 

> Can sm1 plz say y the heck is clear() in arr.h not working? Or mb smth else wrong?

**Comment by 4eckah78** [comment]
@exp101t Thank you very much, German! You're probably the only one who checks issues:heart:
Got it👌
I tested this code as with Array::size  becoming 0 and without it, but there was always exception. Can you please say what tests did you test?
**P. S.**  А тут можно на русском?

**Comment by exp101t** [comment]
```
#include <iostream>
using namespace std;

template<typename Data>
class Array {
public:
	Array() {
		arr = nullptr;
		size = 0;
	};
	Array(size_t n) {
		size = n;
		arr = new Data[size];
		for (size_t i = 0; i < size; ++i) {
			*(arr + i) = 0;
		}
	};
	Array(const Array &original) {
		size = original.Size();
		arr = new Data[size];
		for (size_t i = 0; i < size; ++i)
			*(arr + i) = original.getValue(i);
	};
	~Array() {
		clear();
	};
	Data* first() {
		return arr;
	};
	Data* last() {
		return arr + this->size;
	};

	void clear() {
		if (!isVoid())
			delete[] arr;
	};
	void addData(Array a, Data data) {
		Data* tmp = new Data[a.Size()];
		for (int i = 0; i < a.Size(); ++i)
			tmp[i] = a.getValue(i);
		arr = new Data[size + 1];
		for (int i = 0; i < a.Size(); ++i)
			arr[i] = tmp[i];
		arr[size] = data;
		size++;
	};
	Data* pointer()const {
		return arr;
	};
	size_t Size()const{
		return size;
    };
	Data getValue(size_t i)const {
		if (i < size)
			return *(arr + i);
	};
	void changeValue(size_t i, Data data) {
		if (i < Size())
			*(arr + i) = data;
	};
	void printArray() {
		for (size_t i = 0; i < Size(); ++i)
			cout << *(arr + i) << " ";
	};
	bool isVoid()const {
		return Size() == 0;
	};
	void deleteElement(size_t i) {
		if (i < Size()) {
			for (int j = i; j < Size() - 1; ++j)
				*(arr + i) = *(arr + j + 1);
			size--;
		}
	};
	Data operator[](int ind) {
		if ((ind < size) && (ind > -1))
			return *(arr + ind);
		return -123452;
	};
    Data * arr;
private:

	size_t size;
};

int main() {
    Array<int> test = Array<int>(10);
    test.changeValue(2, 17);
    test.printArray();
    test.clear();
    return 0;
}
```

**Comment by exp101t** [comment]
And yes, you can not delete `arr` after it has been deleted in `Array::clear()`. Therefore, destructor throws an exception.

**Comment by 4eckah78** [comment]
I made some changes in `Array::clear()` and `Array::~Array()` but this test:
```
while (1) {
  Array<int> arr;
  arr.addData(2);
}
```
show that `Array::~Array()` is not working properly

**Comment by exp101t** [comment]
I have no idea how this test shows that destructor isn't working properly

**Comment by exp101t** [comment]
You have to delete `tmp` and old `arr` in `Array::addData`. Now this method causes memory leak.

**Comment by 4eckah78** [comment]
Guys! I must say that this issue is officially closed! 
*applause*
